USE CDWD;

DROP TABLE IF EXISTS ANSI_AREAS;
CREATE TABLE ANSI_AREAS (
	ANSI_STATE_CODE      INT,
	ANSI_ENTITY_CODE     INT,
	ANSI_NAME            VARCHAR(255),
	STATE_CODE           VARCHAR(2)
) ENGINE = InnoDB;


LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/ANSI_AREAS.csv'
INTO TABLE ANSI_AREAS 
FIELDS TERMINATED BY ','
ESCAPED BY ''
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@ANSI_STATE_CODE,@ANSI_ENTITY_CODE,@ANSI_NAME,@STATE_CODE)
SET
ANSI_STATE_CODE = IF(@ANSI_STATE_CODE = '', NULL, @ANSI_STATE_CODE),
ANSI_ENTITY_CODE = IF(@ANSI_ENTITY_CODE = '', NULL, @ANSI_ENTITY_CODE),
ANSI_NAME = IF(@ANSI_NAME = '', NULL, @ANSI_NAME),
STATE_CODE = IF(@STATE_CODE = '', NULL, @STATE_CODE);

SELECT COUNT(*) From ansi_areas;


-- Adding index for effective filtering using select query
ALTER TABLE ANSI_AREAS
ADD INDEX idx_ANSI_STATE_CODE (ANSI_STATE_CODE);

ALTER TABLE ANSI_AREAS
ADD INDEX idx_STATE_CODE (STATE_CODE);

ALTER TABLE ANSI_AREAS
ADD INDEX idx_ANSI_ENTITY_CODE (ANSI_ENTITY_CODE);
