
USE CDWD;

DROP TABLE IF EXISTS GEOGRAPHIC_AREAS;
CREATE TABLE GEOGRAPHIC_AREAS (
	SUBMISSIONYEARQUARTER     VARCHAR(6),
	PWSID                     VARCHAR(9),
	GEO_ID                    VARCHAR(8),
	AREA_TYPE_CODE            VARCHAR(10),
	TRIBAL_CODE               VARCHAR(10),
	STATE_SERVED              VARCHAR(2),
	ANSI_ENTITY_CODE          VARCHAR(3),
	ZIP_CODE_SERVED           VARCHAR(15),
	CITY_SERVED               VARCHAR(40),
	COUNTY_SERVED             VARCHAR(50),
	LAST_REPORTED_DATE        DATE,
PRIMARY KEY(GEO_ID)
) ENGINE = InnoDB;


LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/GEOGRAPHIC_AREAS.csv'
INTO TABLE GEOGRAPHIC_AREAS 
FIELDS TERMINATED BY ','
ESCAPED BY ''
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@SUBMISSIONYEARQUARTER,@PWSID,@GEO_ID,@AREA_TYPE_CODE,@TRIBAL_CODE,@STATE_SERVED,@ANSI_ENTITY_CODE,@ZIP_CODE_SERVED,@CITY_SERVED,@COUNTY_SERVED,@LAST_REPORTED_DATE)
SET
SUBMISSIONYEARQUARTER = IF(@SUBMISSIONYEARQUARTER = '', NULL, @SUBMISSIONYEARQUARTER),
PWSID = IF(@PWSID = '', NULL, @PWSID),
GEO_ID = IF(@GEO_ID = '', NULL, @GEO_ID),
AREA_TYPE_CODE = IF(@AREA_TYPE_CODE = '', NULL, @AREA_TYPE_CODE),
TRIBAL_CODE = IF(@TRIBAL_CODE = '', NULL, @TRIBAL_CODE),
STATE_SERVED = IF(@STATE_SERVED = '', NULL, @STATE_SERVED),
ANSI_ENTITY_CODE = IF(@ANSI_ENTITY_CODE = '', NULL, @ANSI_ENTITY_CODE),
ZIP_CODE_SERVED = IF(@ZIP_CODE_SERVED = '', NULL, @ZIP_CODE_SERVED),
CITY_SERVED = IF(@CITY_SERVED = '', NULL, @CITY_SERVED),
COUNTY_SERVED = IF(@COUNTY_SERVED = '', NULL, @COUNTY_SERVED),
LAST_REPORTED_DATE = IF(@LAST_REPORTED_DATE = '', NULL, STR_TO_DATE(@LAST_REPORTED_DATE, '%Y-%m-%d'));

-- Adding index for effective filtering using select query
ALTER TABLE GEOGRAPHIC_AREAS
ADD INDEX idx_PWSID (PWSID);

ALTER TABLE GEOGRAPHIC_AREAS
ADD INDEX idx_AREA_TYPE_CODE (AREA_TYPE_CODE);

ALTER TABLE GEOGRAPHIC_AREAS
ADD INDEX idx_TRIBAL_CODE (TRIBAL_CODE);

ALTER TABLE GEOGRAPHIC_AREAS
ADD INDEX idx_STATE_SERVED (STATE_SERVED);

ALTER TABLE GEOGRAPHIC_AREAS
ADD INDEX idx_ANSI_ENTITY_CODE (ANSI_ENTITY_CODE);

ALTER TABLE GEOGRAPHIC_AREAS
ADD INDEX idx_ZIP_CODE_SERVED (ZIP_CODE_SERVED);

ALTER TABLE GEOGRAPHIC_AREAS
ADD INDEX idx_CITY_SERVED (CITY_SERVED);

ALTER TABLE GEOGRAPHIC_AREAS
ADD INDEX idx_COUNTY_SERVED (COUNTY_SERVED);