USE CDWD;

DROP TABLE IF EXISTS LCR_SAMPLES;
CREATE TABLE LCR_SAMPLES (
	SUBMISSIONYEARQUARTER          VARCHAR(6),
	PWSID                          VARCHAR(9),
	SAMPLE_ID                      VARCHAR(255),
	SAMPLING_END_DATE              DATE,
	SAMPLING_START_DATE            DATE,
	RECONCILIATION_ID              VARCHAR(40),
	SAMPLE_FIRST_REPORTED_DATE     DATE,
	SAMPLE_LAST_REPORTED_DATE      DATE,
	SAR_ID                         INT,
	CONTAMINANT_CODE               VARCHAR(4),
	RESULT_SIGN_CODE               VARCHAR(2),
	SAMPLE_MEASURE                 INT,
	UNIT_OF_MEASURE                VARCHAR(4),
	SAR_FIRST_REPORTED_DATE        DATE,
	SAR_LAST_REPORTED_DATE         DATE
) ENGINE = InnoDB;

LOAD DATA INFILE '/Users/audacious/Desktop/CDWD/Uploads/LCR_SAMPLES.csv'
INTO TABLE LCR_SAMPLES 
FIELDS TERMINATED BY ','
ESCAPED BY ''
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@SUBMISSIONYEARQUARTER,@PWSID,@SAMPLE_ID,@SAMPLING_END_DATE,@SAMPLING_START_DATE,@RECONCILIATION_ID,@SAMPLE_FIRST_REPORTED_DATE,@SAMPLE_LAST_REPORTED_DATE,@SAR_ID,@CONTAMINANT_CODE,@RESULT_SIGN_CODE,@SAMPLE_MEASURE,@UNIT_OF_MEASURE,@SAR_FIRST_REPORTED_DATE,@SAR_LAST_REPORTED_DATE)
SET
SUBMISSIONYEARQUARTER = IF(@SUBMISSIONYEARQUARTER = '', NULL, @SUBMISSIONYEARQUARTER),
PWSID = IF(@PWSID = '', NULL, @PWSID),
SAMPLE_ID = IF(@SAMPLE_ID = '', NULL, @SAMPLE_ID),
SAMPLING_END_DATE = IF(@SAMPLING_END_DATE = '', NULL, STR_TO_DATE(@SAMPLING_END_DATE, '%Y-%m-%d')),
SAMPLING_START_DATE = IF(@SAMPLING_START_DATE = '', NULL, STR_TO_DATE(@SAMPLING_START_DATE, '%Y-%m-%d')),
RECONCILIATION_ID = IF(@RECONCILIATION_ID = '', NULL, @RECONCILIATION_ID),
SAMPLE_FIRST_REPORTED_DATE = IF(@SAMPLE_FIRST_REPORTED_DATE = '', NULL, STR_TO_DATE(@SAMPLE_FIRST_REPORTED_DATE, '%Y-%m-%d')),
SAMPLE_LAST_REPORTED_DATE = IF(@SAMPLE_LAST_REPORTED_DATE = '', NULL, STR_TO_DATE(@SAMPLE_LAST_REPORTED_DATE, '%Y-%m-%d')),
SAR_ID = IF(@SAR_ID = '', NULL, @SAR_ID),
CONTAMINANT_CODE = IF(@CONTAMINANT_CODE = '', NULL, @CONTAMINANT_CODE),
RESULT_SIGN_CODE = IF(@RESULT_SIGN_CODE = '', NULL, @RESULT_SIGN_CODE),
SAMPLE_MEASURE = IF(@SAMPLE_MEASURE = '', NULL, @SAMPLE_MEASURE),
UNIT_OF_MEASURE = IF(@UNIT_OF_MEASURE = '', NULL, @UNIT_OF_MEASURE),
SAR_FIRST_REPORTED_DATE = IF(@SAR_FIRST_REPORTED_DATE = '', NULL, STR_TO_DATE(@SAR_FIRST_REPORTED_DATE, '%Y-%m-%d')),
SAR_LAST_REPORTED_DATE = IF(@SAR_LAST_REPORTED_DATE = '', NULL, STR_TO_DATE(@SAR_LAST_REPORTED_DATE, '%Y-%m-%d'));

-- Adding index for effective filtering using select query
ALTER TABLE LCR_SAMPLES
ADD INDEX idx_pwsid (PWSID);

ALTER TABLE LCR_SAMPLES
ADD INDEX idx_sample_id (SAMPLE_ID);

ALTER TABLE LCR_SAMPLES
ADD INDEX idx_SAMPLING_END_DATE (SAMPLING_END_DATE);

ALTER TABLE LCR_SAMPLES
ADD INDEX idx_SAMPLING_START_DATE (SAMPLING_START_DATE);

ALTER TABLE LCR_SAMPLES
ADD INDEX idx_CONTAMINANT_CODE (CONTAMINANT_CODE);

ALTER TABLE LCR_SAMPLES
ADD INDEX idx_RESULT_SIGN_CODE (RESULT_SIGN_CODE);

ALTER TABLE LCR_SAMPLES
ADD INDEX idx_SAMPLE_MEASURE (SAMPLE_MEASURE);