USE CDWD;

CREATE TABLE SERVICE_AREAS (
	SUBMISSIONYEARQUARTER            VARCHAR(6),
	PWSID                            VARCHAR(9),
	SERVICE_AREA_TYPE_CODE           VARCHAR(4),
	IS_PRIMARY_SERVICE_AREA_CODE     VARCHAR(1),
	FIRST_REPORTED_DATE              DATE,
	LAST_REPORTED_DATE               DATE
) ENGINE = InnoDB;

SET sql_mode = '';

LOAD DATA INFILE '/Users/audacious/Desktop/CDWD/Uploads/SERVICE_AREAS.csv'
INTO TABLE SERVICE_AREAS 
FIELDS TERMINATED BY ','
ESCAPED BY ''
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@SUBMISSIONYEARQUARTER,@PWSID,@SERVICE_AREA_TYPE_CODE,@IS_PRIMARY_SERVICE_AREA_CODE,@FIRST_REPORTED_DATE,@LAST_REPORTED_DATE)
SET
SUBMISSIONYEARQUARTER = IF(@SUBMISSIONYEARQUARTER = '', NULL, @SUBMISSIONYEARQUARTER),
PWSID = IF(@PWSID = '', NULL, @PWSID),
SERVICE_AREA_TYPE_CODE = IF(@SERVICE_AREA_TYPE_CODE = '', NULL, @SERVICE_AREA_TYPE_CODE),
IS_PRIMARY_SERVICE_AREA_CODE = IF(@IS_PRIMARY_SERVICE_AREA_CODE = '', NULL, @IS_PRIMARY_SERVICE_AREA_CODE),
FIRST_REPORTED_DATE = IF(@FIRST_REPORTED_DATE = '', NULL, STR_TO_DATE(@FIRST_REPORTED_DATE, '%Y-%m-%d')),
LAST_REPORTED_DATE = IF(@LAST_REPORTED_DATE = '', NULL, STR_TO_DATE(@LAST_REPORTED_DATE, '%Y-%m-%d'));

-- Adding index for effective filtering using select query
ALTER TABLE SERVICE_AREAS
ADD INDEX idx_PWSID (PWSID);

ALTER TABLE SERVICE_AREAS
ADD INDEX idx_SERVICE_AREA_TYPE_CODE (SERVICE_AREA_TYPE_CODE);

ALTER TABLE SERVICE_AREAS
ADD INDEX idx_IS_PRIMARY_SERVICE_AREA_CODE (IS_PRIMARY_SERVICE_AREA_CODE);
