USE CDWD;

DROP TABLE IF EXISTS SITE_VISIT;
CREATE TABLE SITE_VISIT (
	SUBMISSIONYEARQUARTER             VARCHAR(6),
	PWSID                             VARCHAR(9),
	VISIT_ID                          VARCHAR(255),
	VISIT_DATE                        DATE,
	AGENCY_TYPE_CODE                  VARCHAR(4),
	VISIT_REASON_CODE                 VARCHAR(4),
	MANAGEMENT_OPS_EVAL_CODE          VARCHAR(1),
	SOURCE_WATER_EVAL_CODE            VARCHAR(1),
	SECURITY_EVAL_CODE                VARCHAR(1),
	PUMPS_EVAL_CODE                   VARCHAR(1),
	OTHER_EVAL_CODE                   VARCHAR(1),
	COMPLIANCE_EVAL_CODE              VARCHAR(1),
	DATA_VERIFICATION_EVAL_CODE       VARCHAR(1),
	TREATMENT_EVAL_CODE               VARCHAR(1),
	FINISHED_WATER_STOR_EVAL_CODE     VARCHAR(1),
	DISTRIBUTION_EVAL_CODE            VARCHAR(1),
	FINANCIAL_EVAL_CODE               VARCHAR(1),
	VISIT_COMMENTS                    TEXT,
	FIRST_REPORTED_DATE               DATE,
	LAST_REPORTED_DATE                DATE
) ENGINE = InnoDB;



LOAD DATA INFILE '/Users/audacious/Desktop/CDWD/Uploads/SDWA_SITE_VISITS.csv'
INTO TABLE SITE_VISIT
FIELDS TERMINATED BY ','
ESCAPED BY ''
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@SUBMISSIONYEARQUARTER,@PWSID,@VISIT_ID,@VISIT_DATE,@AGENCY_TYPE_CODE,@VISIT_REASON_CODE,@MANAGEMENT_OPS_EVAL_CODE,@SOURCE_WATER_EVAL_CODE,@SECURITY_EVAL_CODE,@PUMPS_EVAL_CODE,@OTHER_EVAL_CODE,@COMPLIANCE_EVAL_CODE,@DATA_VERIFICATION_EVAL_CODE,@TREATMENT_EVAL_CODE,@FINISHED_WATER_STOR_EVAL_CODE,@DISTRIBUTION_EVAL_CODE,@FINANCIAL_EVAL_CODE,@VISIT_COMMENTS,@FIRST_REPORTED_DATE,@LAST_REPORTED_DATE)
SET
SUBMISSIONYEARQUARTER = IF(@SUBMISSIONYEARQUARTER = '', NULL, @SUBMISSIONYEARQUARTER),
PWSID = IF(@PWSID = '', NULL, @PWSID),
VISIT_ID = IF(@VISIT_ID = '', NULL, @VISIT_ID),
VISIT_DATE = IF(@VISIT_DATE = '', NULL, STR_TO_DATE(@VISIT_DATE, '%m/%d/%Y')),
AGENCY_TYPE_CODE = IF(@AGENCY_TYPE_CODE = '', NULL, @AGENCY_TYPE_CODE),
VISIT_REASON_CODE = IF(@VISIT_REASON_CODE = '', NULL, @VISIT_REASON_CODE),
MANAGEMENT_OPS_EVAL_CODE = IF(@MANAGEMENT_OPS_EVAL_CODE = '', NULL, @MANAGEMENT_OPS_EVAL_CODE),
SOURCE_WATER_EVAL_CODE = IF(@SOURCE_WATER_EVAL_CODE = '', NULL, @SOURCE_WATER_EVAL_CODE),
SECURITY_EVAL_CODE = IF(@SECURITY_EVAL_CODE = '', NULL, @SECURITY_EVAL_CODE),
PUMPS_EVAL_CODE = IF(@PUMPS_EVAL_CODE = '', NULL, @PUMPS_EVAL_CODE),
OTHER_EVAL_CODE = IF(@OTHER_EVAL_CODE = '', NULL, @OTHER_EVAL_CODE),
COMPLIANCE_EVAL_CODE = IF(@COMPLIANCE_EVAL_CODE = '', NULL, @COMPLIANCE_EVAL_CODE),
DATA_VERIFICATION_EVAL_CODE = IF(@DATA_VERIFICATION_EVAL_CODE = '', NULL, @DATA_VERIFICATION_EVAL_CODE),
TREATMENT_EVAL_CODE = IF(@TREATMENT_EVAL_CODE = '', NULL, @TREATMENT_EVAL_CODE),
FINISHED_WATER_STOR_EVAL_CODE = IF(@FINISHED_WATER_STOR_EVAL_CODE = '', NULL, @FINISHED_WATER_STOR_EVAL_CODE),
DISTRIBUTION_EVAL_CODE = IF(@DISTRIBUTION_EVAL_CODE = '', NULL, @DISTRIBUTION_EVAL_CODE),
FINANCIAL_EVAL_CODE = IF(@FINANCIAL_EVAL_CODE = '', NULL, @FINANCIAL_EVAL_CODE),
VISIT_COMMENTS = IF(@VISIT_COMMENTS = '', NULL, @VISIT_COMMENTS),
FIRST_REPORTED_DATE = IF(@FIRST_REPORTED_DATE = '', NULL, STR_TO_DATE(@FIRST_REPORTED_DATE, '%m/%d/%Y')),
LAST_REPORTED_DATE = IF(@LAST_REPORTED_DATE = '', NULL, STR_TO_DATE(@LAST_REPORTED_DATE, '%m/%d/%Y'));

select * from site_visit;

/*
PWSID
VISIT_ID
VISIT_DATE
AGENCY_TYPE_CODE
VISIT_REASON_CODE
*/

-- Adding index for effective filtering using select query
ALTER TABLE site_visit
ADD INDEX idx_PWSID (PWSID);

ALTER TABLE site_visit
ADD INDEX idx_VISIT_ID (VISIT_ID);

ALTER TABLE site_visit
ADD INDEX idx_VISIT_DATE (VISIT_DATE);

ALTER TABLE site_visit
ADD INDEX idx_AGENCY_TYPE_CODE (AGENCY_TYPE_CODE);

ALTER TABLE site_visit
ADD INDEX idx_VISIT_REASON_CODE (VISIT_REASON_CODE);